import { PresetsThemeType } from "../types/theme/preset.theme.type";
import { ScrollToFutureThemeProps } from "../types/theme/scroll-to-future.theme.type";
import {
    arctic,
    candy,
    deepSea,
    ember,
    forest,
    glass,
    gold,
    graphite,
    lava,
    midnight,
    monoDark,
    monoLight,
    moss,
    neonCyan,
    ocean,
    primary,
    roseQuartz,
    royal,
    sand,
    terminal,
    toxic,
    violet,
} from "./collection.theme";

export const presets: Record<PresetsThemeType, ScrollToFutureThemeProps> = {
    primary,
    midnight,
    neonCyan,
    ocean,
    deepSea,
    forest,
    moss,
    lava,
    ember,
    gold,
    roseQuartz,
    violet,
    royal,
    arctic,
    glass,
    graphite,
    terminal,
    toxic,
    candy,
    sand,
    monoLight,
    monoDark,
};
